/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutPromotionsRouteImport } from './routes/_layout.promotions'
import { Route as LayoutProductsRouteImport } from './routes/_layout.products'
import { Route as LayoutOrdersRouteImport } from './routes/_layout.orders'
import { Route as LayoutMenuCatalogRouteImport } from './routes/_layout.menu-catalog'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPromotionsRoute = LayoutPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMenuCatalogRoute = LayoutMenuCatalogRouteImport.update({
  id: '/menu-catalog',
  path: '/menu-catalog',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/menu-catalog': typeof LayoutMenuCatalogRoute
  '/orders': typeof LayoutOrdersRoute
  '/products': typeof LayoutProductsRoute
  '/promotions': typeof LayoutPromotionsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/menu-catalog': typeof LayoutMenuCatalogRoute
  '/orders': typeof LayoutOrdersRoute
  '/products': typeof LayoutProductsRoute
  '/promotions': typeof LayoutPromotionsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/menu-catalog': typeof LayoutMenuCatalogRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/promotions': typeof LayoutPromotionsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/menu-catalog'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/menu-catalog'
    | '/orders'
    | '/products'
    | '/promotions'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/menu-catalog'
    | '/_layout/orders'
    | '/_layout/products'
    | '/_layout/promotions'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/promotions': {
      id: '/_layout/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof LayoutPromotionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/menu-catalog': {
      id: '/_layout/menu-catalog'
      path: '/menu-catalog'
      fullPath: '/menu-catalog'
      preLoaderRoute: typeof LayoutMenuCatalogRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutMenuCatalogRoute: typeof LayoutMenuCatalogRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutPromotionsRoute: typeof LayoutPromotionsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMenuCatalogRoute: LayoutMenuCatalogRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutPromotionsRoute: LayoutPromotionsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
